<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc" style="margin-top: 1em;"><ul class="toc-item"></ul></div>

In [1]:
import os
import pandas as pd

In [2]:
a = pd.read_csv("./data/counts_simulated_dataset1_dropout0.05.csv")
b = pd.read_csv("./data/true_counts_simulated_dataset1_dropout0.05.csv")

In [6]:
a.describe()

Cell1        Cell2        Cell3        Cell4        Cell5  \
count  5000.000000  5000.000000  5000.000000  5000.000000  5000.000000   
mean      5.845000     4.659600     3.910800     6.585600     4.283600   
std      25.924965    21.993755    17.849677    30.856965    21.296138   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       2.000000     2.000000     1.000000     2.000000     1.000000   
max     478.000000   492.000000   301.000000   583.000000   486.000000   

             Cell6        Cell7        Cell8        Cell9       Cell10  \
count  5000.000000  5000.000000  5000.000000  5000.000000  5000.000000   
mean      6.660600     5.068600     6.197400     3.626400     4.904800   
std      29.829082    25.418157    29.266885    16.564592    22.448219   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       3.000000     2.000000     2.000000     1.000000     2.000000   
max     596.000000   579.000000   600.000000   307.000000   489.000000   

          ...         Cell1991     Cell1992     Cell1993     Cell1994  \
count     ...       5000.00000  5000.000000  5000.000000  5000.000000   
mean      ...          5.13080     5.543400     6.817200     4.500000   
std       ...         24.26134    25.630308    31.864238    19.917353   
min       ...          0.00000     0.000000     0.000000     0.000000   
25%       ...          0.00000     0.000000     0.000000     0.000000   
50%       ...          0.00000     0.000000     0.000000     0.000000   
75%       ...          2.00000     2.000000     2.000000     2.000000   
max       ...        483.00000   509.000000   611.000000   409.000000   

          Cell1995     Cell1996     Cell1997     Cell1998    Cell1999  \
count  5000.000000  5000.000000  5000.000000  5000.000000  5000.00000   
mean      4.140200     4.838200     4.853800     5.040400     6.39580   
std      19.637313    23.690409    21.693228    23.514161    31.29461   
min       0.000000     0.000000     0.000000     0.000000     0.00000   
25%       0.000000     0.000000     0.000000     0.000000     0.00000   
50%       0.000000     0.000000     0.000000     0.000000     0.00000   
75%       1.000000     2.000000     2.000000     2.000000     2.00000   
max     440.000000   577.000000   413.000000   473.000000   640.00000   

          Cell2000  
count  5000.000000  
mean      5.036200  
std      24.569315  
min       0.000000  
25%       0.000000  
50%       0.000000  
75%       2.000000  
max     468.000000  

[8 rows x 2000 columns]

In [7]:
b.describe()

Cell1        Cell2        Cell3        Cell4        Cell5  \
count  5000.00000  5000.000000  5000.000000  5000.000000  5000.000000   
mean     13.89940    10.759600     8.524400    14.274200     9.444600   
std      43.45673    34.126188    26.476087    44.125526    29.987957   
min       0.00000     0.000000     0.000000     0.000000     0.000000   
25%       0.00000     0.000000     0.000000     0.000000     0.000000   
50%       3.00000     2.000000     1.000000     3.000000     2.000000   
75%       9.00000     7.000000     5.000000     9.000000     6.000000   
max     686.00000   652.000000   363.000000   667.000000   486.000000   

             Cell6        Cell7        Cell8       Cell9       Cell10  \
count  5000.000000  5000.000000  5000.000000  5000.00000  5000.000000   
mean     13.783800    10.193400    13.286600     8.84500    10.968600   
std      43.007122    32.400993    41.527111    27.55402    33.767844   
min       0.000000     0.000000     0.000000     0.00000     0.000000   
25%       0.000000     0.000000     0.000000     0.00000     0.000000   
50%       3.000000     2.000000     2.000000     2.00000     2.000000   
75%       9.000000     7.000000     9.000000     6.00000     7.000000   
max     750.000000   579.000000   600.000000   385.00000   572.000000   

          ...          Cell1991     Cell1992     Cell1993     Cell1994  \
count     ...       5000.000000  5000.000000  5000.000000  5000.000000   
mean      ...         11.253800    12.394600    14.736800    10.195000   
std       ...         35.048479    38.645357    45.860996    31.098997   
min       ...          0.000000     0.000000     0.000000     0.000000   
25%       ...          0.000000     0.000000     0.000000     0.000000   
50%       ...          2.000000     2.000000     3.000000     2.000000   
75%       ...          8.000000     8.000000    10.000000     7.000000   
max       ...        483.000000   553.000000   699.000000   428.000000   

          Cell1995     Cell1996     Cell1997     Cell1998     Cell1999  \
count  5000.000000  5000.000000  5000.000000  5000.000000  5000.000000   
mean      8.913800    10.338600    10.694600    10.483200    12.965600   
std      28.024715    32.453237    33.027011    33.275456    40.932548   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       1.000000     2.000000     2.000000     2.000000     2.000000   
75%       6.000000     7.000000     7.000000     7.000000     8.000000   
max     440.000000   577.000000   483.000000   484.000000   640.000000   

          Cell2000  
count  5000.000000  
mean     12.711200  
std      39.913426  
min       0.000000  
25%       0.000000  
50%       2.000000  
75%       8.000000  
max     711.000000  

[8 rows x 2000 columns]

In [82]:
max_i = 0
for i in b.max()[1:]:
    max_i = i if i > max_i else max_i

In [83]:
max_i

1231

In [43]:
n = np.asarray(a.iloc[:, 1:])

In [46]:
np.mean(n)

5.4303905

In [47]:
np.std(n)

26.18158104312096

In [48]:
n

array([[ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  8,  2,  0],
       [ 0,  0,  0, ...,  5,  0, 19],
       ...,
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  1]])

In [52]:
t = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize(mean = (1,1,0.5), std = (0.5,1,1))
])

t(n)

tensor([[[ 0,  0,  0,  ...,  0,  0,  0],
         [ 0,  0,  0,  ...,  8,  2,  0],
         [ 0,  0,  0,  ...,  5,  0, 19],
         ...,
         [ 0,  0,  0,  ...,  0,  0,  0],
         [ 0,  0,  0,  ...,  0,  0,  0],
         [ 0,  0,  0,  ...,  0,  0,  1]]])

In [55]:
n/np.std(n)

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.30555832, 0.07638958,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.19097395, 0.        ,
        0.72570102],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.03819479]])

In [ ]:
import os

import torch
from torch import nn
from torch.autograd import Variable
from torch.utils.data import DataLoader, Dataset
from torchvision import transforms
from torchvision.utils import save_image
from scipy.stats.stats import pearsonr
from Progbar import Progbar

import pandas as pd
import numpy as np

if not os.path.exists('./mlp_img'):
    os.mkdir('./mlp_img')
if not os.path.exists('./filters'):
    os.mkdir('./filters')
device = torch.device("cuda:0" if torch.cuda.is_available() else 'cpu')

def to_img(x):
    x = x.view(x.size(0), 1, 100, 50)
    return x

num_epochs = 10
batch_size = 50
learning_rate = 1e-3

class SimulatedDataset(Dataset):
    '''
    每一个 Item 是 (5000, ) 的向量
    '''

    def __init__(self, simulated_csv_data_path, true_csv_data_path, transform=None):
        self.simulated_csv_data = pd.read_csv(simulated_csv_data_path)
        self.true_csv_data_path = pd.read_csv(true_csv_data_path)
        self.transform = transform

    def __len__(self):
        return len(self.simulated_csv_data.columns) - 1

    def __getitem__(self, index):
        a_column_of_simulated_data = self.simulated_csv_data.iloc[:, index+1]
        a_column_of_true_data = self.true_csv_data_path.iloc[:, index+1]
        a_column_of_simulated_data = np.asarray(a_column_of_simulated_data).reshape(1,-1)
        a_column_of_true_data = np.asarray(a_column_of_true_data).reshape(1,-1)
        
        a_column_of_simulated_data = a_column_of_simulated_data / np.max(a_column_of_simulated_data)
        a_column_of_true_data = a_column_of_true_data / np.max(a_column_of_true_data)
#         if self.transform is not None:
#             a_column_of_simulated_data = self.transform(a_column_of_simulated_data)
#             a_column_of_true_data = self.transform(a_column_of_true_data)
        simulated_true_pack = (a_column_of_simulated_data, a_column_of_true_data)
        return simulated_true_pack

class AutoEncoder(nn.Module):
    def __init__(self):
        super(AutoEncoder, self).__init__()
        self.encoder = nn.Sequential(
            nn.Linear(5000, 512),
            nn.ReLU(True),
            nn.Linear(512, 128),
            nn.ReLU(True),
            nn.Linear(128, 64),
            nn.ReLU(True))
        self.decoder = nn.Sequential(
            nn.Linear(64, 128),
            nn.ReLU(True),
            nn.Linear(128, 512),
            nn.ReLU(True),
            nn.Linear(512, 5000),
            nn.Sigmoid())

    def forward(self, x):
        x = self.encoder(x)
        x = self.decoder(x)
        return x    

In [77]:
dataset = SimulatedDataset(simulated_csv_data_path="./data/counts_simulated_dataset1_dropout0.05.csv",
                           true_csv_data_path="./data/true_counts_simulated_dataset1_dropout0.05.csv")
dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=True, num_workers=3)
model = AutoEncoder().to(device)
criterion = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate, weight_decay=1e-5)

In [173]:
def predict(simulated_csv_data_path="./data/counts_simulated_dataset1_dropout0.05.csv",
            true_csv_data_path="./data/true_counts_simulated_dataset1_dropout0.05.csv",
            save_model_filename="./model_dropout0.05.pth", num_epochs = 40):
    dataset = SimulatedDataset(simulated_csv_data_path, true_csv_data_path)
    dataloader = DataLoader(dataset, batch_size=100, shuffle=True, num_workers=3)
    model = AutoEncoder().to(device)
    criterion = nn.MSELoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=1e-3, weight_decay=1e-5)
    if os.path.exists(save_model_filename):
        model.load_state_dict(torch.load(save_model_filename, "cpu"))
    else:
        model.train()
        for epoch in range(num_epochs):
            prog = Progbar(len(dataloader))
            for i, data in enumerate(dataloader):
                (noisy_data, true_data) = data
                noisy_data = Variable(noisy_data).float().to(device)
                true_data = Variable(true_data).float().to(device)
                # ===================forward=====================
                output = model(noisy_data)
                loss = criterion(output, true_data)
                MSE_loss = nn.MSELoss()(output, true_data)
                np1 = output.cpu().detach().numpy().reshape(-1)
                np2 = true_data.cpu().detach().numpy().reshape(-1)
                PCC, p_value = pearsonr(np1, np2)
                # ===================backward====================
                optimizer.zero_grad()
                loss.backward()
                optimizer.step()
                # =====================log=======================
                prog.update(i + 1, [("loss", loss.item()), ("MSE_loss", MSE_loss.data), ("PCC", PCC), ("p-value", p_value)])
            # ===================log========================
            print('epoch [{}/{}], loss:{:.4f}, MSE_loss:{:.4f}, PCC:{:.4f}, p-value:{:.4f}'
                  .format(epoch + 1, num_epochs, loss.data, MSE_loss.data, PCC, p_value))
        torch.save(model.state_dict(), save_model_filename)
        
    model.eval()
    dataloader2 = DataLoader(dataset, batch_size=2000, shuffle=True, num_workers=3)
    for data in dataloader2:
        (noisy_data, true_data) = data
        noisy_data = Variable(noisy_data).float().to(device)
        true_data = Variable(true_data).float().to(device)
        # ===================forward=====================
        output = model(noisy_data)
        loss = criterion(output, true_data)
        MSE_loss = nn.MSELoss()(output, true_data)
        np1 = output.cpu().detach().numpy().reshape(-1)
        np2 = true_data.cpu().detach().numpy().reshape(-1)
        PCC, p_value = pearsonr(np1, np2)
#         print('loss:{:.4f}, MSE_loss:{:.4f}, PCC:{:.4f}, p-value:{:.4f}'
#               .format(loss.data, MSE_loss.data, PCC, p_value))
        mse=MSE_loss.data
        o_np_1 = output.data.numpy()
        a = pd.read_csv(simulated_csv_data_path)
        b = pd.read_csv(true_csv_data_path)
        for i in range(2000):
            a.iloc[:, i+1] = np.asarray(np.floor(o_np_1[i][0] * (np.max(a.iloc[:, i+1]))), dtype="int")
        def getPCC(arr1, arr2):
            PCC, p_value = pearsonr(
                np.asarray(arr1).reshape(2000*5000), 
                np.asarray(arr2).reshape(2000*5000))
            return PCC
        pcc = getPCC(a.iloc[:,1:],b.iloc[:,1:])
        print("predict PCC:{:.4f} MSE:{:.8f}".format(pcc,mse))
        a.to_csv("./data/predict_PCC_{:.4f}_MSE_{:.8f}_".format(pcc,mse)+simulated_csv_data_path[7:])

In [177]:
predict(
    "./data/counts_simulated_dataset1_dropout0.05.csv",
    "./data/true_counts_simulated_dataset1_dropout0.05.csv",
    "./model_dropout0.05.pth"
)
predict(
    "./data/counts_simulated_dataset1_dropout0.10.csv",
    "./data/true_counts_simulated_dataset1_dropout0.10.csv",
    "./model_dropout0.10.pth"
)
predict(
    "./data/counts_simulated_dataset1_dropout0.15.csv",
    "./data/true_counts_simulated_dataset1_dropout0.15.csv",
    "./model_dropout0.15.pth"
)
predict(
    "./data/counts_simulated_dataset1_dropout0.20.csv",
    "./data/true_counts_simulated_dataset1_dropout0.20.csv",
    "./model_dropout0.20.pth"
)
predict(
    "./data/counts_simulated_dataset1_dropout0.25.csv",
    "./data/true_counts_simulated_dataset1_dropout0.25.csv",
    "./model_dropout0.25.pth"
)

predict PCC:0.9570 MSE:0.00031984
20/20 [==============================] - 4s - loss: 0.101795 - MSE_loss: 0.101795 - p-value: 0.044509 - PCC: 0.365251     
epoch [1/40], loss:0.0020, MSE_loss:0.0020, PCC:0.7624, p-value:0.0000
20/20 [==============================] - 10s - loss: 0.001519 - MSE_loss: 0.001519 - p-value: 0.000000 - PCC: 0.824836     - ETA: 13s - loss: 0.001710 - MSE_loss: 0.001710 - p-value: 0.
epoch [2/40], loss:0.0013, MSE_loss:0.0013, PCC:0.8516, p-value:0.0000
20/20 [==============================] - 5s - loss: 0.001183 - MSE_loss: 0.001183 - p-value: 0.000000 - PCC: 0.866518     
epoch [3/40], loss:0.0011, MSE_loss:0.0011, PCC:0.8703, p-value:0.0000
20/20 [==============================] - 5s - loss: 0.001101 - MSE_loss: 0.001101 - p-value: 0.000000 - PCC: 0.876389      ETA: 2s - loss: 0.001104 - MSE_loss: 0.001104 - p-value: 0.000000 -
epoch [4/40], loss:0.0011, MSE_loss:0.0011, PCC:0.8786, p-value:0.0000
20/20 [==============================] - 17s - loss: 0.0010

OSError: [Errno 22] Invalid argument

In [117]:
o_np_1 = output1.data.numpy()
o_np_1.shape

(2000, 1, 5000)

In [155]:
"./data/counts_simulated_dataset1_dropout0.05.csv"[7:]

'counts_simulated_dataset1_dropout0.05.csv'

In [104]:
c = pd.read_csv("./data/counts_simulated_dataset1_dropout0.05.csv")

In [118]:
o_np_1[0][0]

array([0.00422271, 0.01117742, 0.01486368, ..., 0.00369527, 0.00381707,
       0.003781  ], dtype=float32)

In [119]:
np.max(c.iloc[:, 1])

478

In [141]:
#c.iloc[:, 1] = 
l = 20
l1 = list(np.asarray(np.floor(o_np_1[0][0] * (np.max(c.iloc[:, 1])))[:l], dtype="int"))
l2 = list(np.asarray(c.iloc[:, 1])[:l])

In [142]:
[l1,l2]

[[2, 5, 7, 1, 2, 2, 2, 3, 2, 2, 2, 1, 4, 98, 1, 2, 1, 10, 2, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 4, 2, 0, 0, 0, 0, 1, 0, 14, 0, 0]]

In [146]:
for i in range(2000):
    c.iloc[:, i+1] = np.asarray(np.floor(o_np_1[i][0] * (np.max(c.iloc[:, i+1]))), dtype="int")

In [147]:
c

Unnamed: 0  Cell1  Cell2  Cell3  Cell4  Cell5  Cell6  Cell7  Cell8  \
0         Gene1      1      2      2      3      1      4      4      2   
1         Gene2      4      6      4      8      4     10     11      6   
2         Gene3      6      8      6     11      6     13     14      8   
3         Gene4      1      2      1      3      1      4      4      2   
4         Gene5      2      3      2      4      2      5      5      2   
5         Gene6      1      2      2      3      1      4      4      2   
6         Gene7      2      3      2      4      2      5      6      3   
7         Gene8      3      3      3      5      2      6      7      3   
8         Gene9      2      2      2      4      2      5      5      2   
9        Gene10      2      2      2      3      2      4      5      2   
10       Gene11      2      2      2      4      2      5      5      2   
11       Gene12      1      2      1      3      1      3      4      1   
12       Gene13      4      5      3      6      3      8      9      4   
13       Gene14     91     98     62    119     92    126    125    114   
14       Gene15      1      2      1      3      1      3      4      1   
15       Gene16      2      2      2      3      1      4      5      2   
16       Gene17      1      2      1      3      1      4      4      2   
17       Gene18     10     12      9     16      9     19     20     12   
18       Gene19      1      2      2      3      1      4      4      2   
19       Gene20      1      2      1      3      1      4      4      2   
20       Gene21      2      2      2      4      2      5      5      2   
21       Gene22      6      7      5     10      6     12     13      7   
22       Gene23      5      7      5      9      5     11     12      6   
23       Gene24      2      2      2      3      2      4      5      2   
24       Gene25      1      2      1      3      1      3      4      1   
25       Gene26      1      2      1      3      1      3      4      1   
26       Gene27      1      2      1      3      1      4      4      2   
27       Gene28      9     11      8     14      8     17     18     10   
28       Gene29      1      2      1      3      1      4      4      2   
29       Gene30      1      2      2      3      1      4      5      2   
...         ...    ...    ...    ...    ...    ...    ...    ...    ...   
4970   Gene4971      3      4      3      6      3      7      8      4   
4971   Gene4972      2      2      2      3      1      4      5      2   
4972   Gene4973      1      2      1      3      1      4      4      2   
4973   Gene4974      1      2      1      3      1      4      4      2   
4974   Gene4975     21     25     17     32     21     36     38     26   
4975   Gene4976      8     10      7     13      8     16     17     10   
4976   Gene4977    406    410    244    479    414    480    460    511   
4977   Gene4978      1      2      1      3      1      4      4      2   
4978   Gene4979      2      3      2      4      2      6      6      3   
4979   Gene4980      5      6      5      8      5     10     11      6   
4980   Gene4981      1      2      2      3      1      4      5      2   
4981   Gene4982      8     10      7     14      8     16     17     10   
4982   Gene4983      2      3      2      5      2      6      6      3   
4983   Gene4984      2      3      2      4      2      5      6      2   
4984   Gene4985     34     38     26     48     33     54     55     41   
4985   Gene4986      2      3      2      4      2      5      5      2   
4986   Gene4987      1      2      1      3      1      3      4      1   
4987   Gene4988    108    115     72    139    109    146    143    135   
4988   Gene4989      7      9      6     12      7     14     15      8   
4989   Gene4990      1      2      1      3      1      4      4      2   
4990   Gene4991      1      2      1      3      1      4      4      2   
4991   Gene4992      3      3 

In [148]:
def getPCC(arr1, arr2):
    PCC, p_value = pearsonr(
        np.asarray(arr1).reshape(2000*5000), 
        np.asarray(arr2).reshape(2000*5000))
    return PCC

In [151]:
pcc = getPCC(b.iloc[:,1:],c.iloc[:,1:])
pcc

0.9554049329950574

In [78]:
#if os.path.exists('./512BCE_sim_autoencoder.pth'):
 #   model.load_state_dict(torch.load('./512BCE_sim_autoencoder.pth', "cpu"))

for epoch in range(num_epochs):
    prog = Progbar(len(dataloader))
    for i, data in enumerate(dataloader):
        (noisy_data, true_data) = data
        noisy_data = Variable(noisy_data).float().to(device)
        true_data = Variable(true_data).float().to(device)
        # ===================forward=====================
        # print(true_data.size())
        output = model(noisy_data)
        loss = criterion(output, true_data)
        MSE_loss = nn.MSELoss()(output, true_data)
        np1 = output.cpu().detach().numpy().reshape(-1)
        np2 = true_data.cpu().detach().numpy().reshape(-1)
        PCC, p_value = pearsonr(np1, np2)
        # ===================backward====================
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        # =====================log=======================
        prog.update(i + 1, [("loss", loss.item()), ("MSE_loss", MSE_loss.data), ("PCC", PCC), ("p-value", p_value)])
    # ===================log========================
    print('epoch [{}/{}], loss:{:.4f}, MSE_loss:{:.4f}, PCC:{:.4f}, p-value:{:.4f}'
          .format(epoch + 1, num_epochs, loss.data, MSE_loss.data, PCC, p_value))

torch.save(model.state_dict(), './512BCE_000_sim_autoencoder.pth')

40/40 [==============================] - 4s - loss: 0.051606 - MSE_loss: 0.051606 - p-value: 0.000000 - PCC: 0.602865      ETA: 2s - loss: 0.106888 - MSE_loss: 0.
epoch [1/10], loss:0.0013, MSE_loss:0.0013, PCC:0.8527, p-value:0.0000
40/40 [==============================] - 4s - loss: 0.001177 - MSE_loss: 0.001177 - p-value: 0.000000 - PCC: 0.866940     
epoch [2/10], loss:0.0011, MSE_loss:0.0011, PCC:0.8793, p-value:0.0000
40/40 [==============================] - 3s - loss: 0.001070 - MSE_loss: 0.001070 - p-value: 0.000000 - PCC: 0.880408      ETA: 0s - loss: 0.001074 - MSE_loss: 0.001074 - p-value: 0.000000 - PCC: 0.87
epoch [3/10], loss:0.0010, MSE_loss:0.0010, PCC:0.8932, p-value:0.0000
40/40 [==============================] - 3s - loss: 0.000934 - MSE_loss: 0.000934 - p-value: 0.000000 - PCC: 0.897409     
epoch [4/10], loss:0.0009, MSE_loss:0.0009, PCC:0.9032, p-value:0.0000
40/40 [==============================] - 3s - loss: 0.000822 - MSE_loss: 0.000822 - p-value: 0.000000 - PC

In [11]:
def save(simulated_csv_data, filename="./image.png"):
    aaa = np.asarray(simulated_csv_data.iloc[:, 1:])
    aaa=torch.Tensor(aaa).float()
    aaa=aaa.view(1, 1, aaa.shape[0], aaa.shape[1])
    save_image(aaa, filename)

In [71]:
for i, data in enumerate(dataloader):
    (noisy_data, true_data) = data
#     print(list(noisy_data)[0][0][0][:500])
#     print(list(true_data)[0][0][0][:500])
    print(list(noisy_data)[0][0][:500])
    print(list(true_data)[0][0][:500])
    noisy_data = Variable(noisy_data).float().to(device)
    true_data = Variable(true_data).float().to(device)
    # ===================forward=====================
    # print(true_data.size())
    output = model(noisy_data)
    print(list(noisy_data)[0][0][0][:500])
    print(list(true_data)[0][0][0][:500])
    print(list(output.data)[0][0][0][:50])
    print(output.data)
    break
    
#     loss = criterion(output, true_data)
#     MSE_loss = nn.MSELoss()(output, true_data)
#     np1 = output.cpu().detach().numpy().reshape(-1)
#     np2 = true_data.cpu().detach().numpy().reshape(-1)
#     PCC, p_value = pearsonr(np1, np2)

tensor([0.0000, 0.0142, 0.0085, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0028, 0.0000, 0.0000, 0.0000, 0.1728, 0.0000, 0.0000, 0.0014, 0.0212,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0028, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0042, 0.0000, 0.0127, 0.0042, 0.0042, 0.0057,
        0.0623, 0.0042, 0.0014, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0014,
        0.0000, 0.0156, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0014, 0.0000,
        0.0127, 0.0028, 0.0000, 0.0482, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0028, 0.0113, 0.0000,
        0.0000, 0.0000, 0.0000, 0.1643, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0057, 0.0028, 0.0085, 0.0212, 0.0241, 0.0000, 0.0000,
        0.0000, 0.0340, 0.0000, 0.0042, 0.0000, 0.0042, 0.0042, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0113, 0.0042, 

RuntimeError: dimension specified as 0 but tensor has no dimensions

In [39]:
import torchvision.transforms as transforms
import numpy as np
from __future__ import print_function

# 定义转换方式，transforms.Compose将多个转换函数组合起来使用
transform1 = transforms.Compose([
    transforms.ToTensor(),
])  #归一化到(0,1)，简单直接除以255

# 定义一个数组
d1 = [1,2,3,4,5,6]
d2 = [4,5,6,7,8,9]
d3 = [7,8,9,10,11,14]
d4 = [11,12,13,14,15,15]
d5 = [d1,d2,d3,d4]
d = np.array([d5,d5,d5],dtype=np.float32)
d_t = np.transpose(d,(1,2,0)) # 转置为类似图像的shape，(H,W,C)，作为transform的输入
# 查看d的shape
print('d.shape: ',d.shape, '\nd_t.shape: ', d_t.shape)

d_t_trans = transform1(d_t) # 直接使用函数归一化

# 手动归一化,下面的两个步骤可以在源码里面找到
d_t_temp = torch.from_numpy(d_t.transpose((2,0,1)))
d_t_trans_man = d_t_temp.float().div(255)

print(d_t_trans.equal(d_t_trans_man))

d.shape:  (3, 4, 6) 
d_t.shape:  (4, 6, 3)
False


In [41]:
transform1(d_t)

tensor([[[ 1.,  2.,  3.,  4.,  5.,  6.],
         [ 4.,  5.,  6.,  7.,  8.,  9.],
         [ 7.,  8.,  9., 10., 11., 14.],
         [11., 12., 13., 14., 15., 15.]],

        [[ 1.,  2.,  3.,  4.,  5.,  6.],
         [ 4.,  5.,  6.,  7.,  8.,  9.],
         [ 7.,  8.,  9., 10., 11., 14.],
         [11., 12., 13., 14., 15., 15.]],

        [[ 1.,  2.,  3.,  4.,  5.,  6.],
         [ 4.,  5.,  6.,  7.,  8.,  9.],
         [ 7.,  8.,  9., 10., 11., 14.],
         [11., 12., 13., 14., 15., 15.]]])

In [40]:
d_t_trans_man

tensor([[[0.0039, 0.0078, 0.0118, 0.0157, 0.0196, 0.0235],
         [0.0157, 0.0196, 0.0235, 0.0275, 0.0314, 0.0353],
         [0.0275, 0.0314, 0.0353, 0.0392, 0.0431, 0.0549],
         [0.0431, 0.0471, 0.0510, 0.0549, 0.0588, 0.0588]],

        [[0.0039, 0.0078, 0.0118, 0.0157, 0.0196, 0.0235],
         [0.0157, 0.0196, 0.0235, 0.0275, 0.0314, 0.0353],
         [0.0275, 0.0314, 0.0353, 0.0392, 0.0431, 0.0549],
         [0.0431, 0.0471, 0.0510, 0.0549, 0.0588, 0.0588]],

        [[0.0039, 0.0078, 0.0118, 0.0157, 0.0196, 0.0235],
         [0.0157, 0.0196, 0.0235, 0.0275, 0.0314, 0.0353],
         [0.0275, 0.0314, 0.0353, 0.0392, 0.0431, 0.0549],
         [0.0431, 0.0471, 0.0510, 0.0549, 0.0588, 0.0588]]])

In [36]:
d_t_trans

tensor([[[ 1.,  2.,  3.,  4.,  5.,  6.],
         [ 4.,  5.,  6.,  7.,  8.,  9.],
         [ 7.,  8.,  9., 10., 11., 14.],
         [11., 12., 13., 14., 15., 15.]],

        [[ 1.,  2.,  3.,  4.,  5.,  6.],
         [ 4.,  5.,  6.,  7.,  8.,  9.],
         [ 7.,  8.,  9., 10., 11., 14.],
         [11., 12., 13., 14., 15., 15.]],

        [[ 1.,  2.,  3.,  4.,  5.,  6.],
         [ 4.,  5.,  6.,  7.,  8.,  9.],
         [ 7.,  8.,  9., 10., 11., 14.],
         [11., 12., 13., 14., 15., 15.]]])